# $Header: /cvs/fluid/fluid/code/fluid/java/control/GNUmakefile,v 1.7 1999/03/01 17:05:18 boyland Exp $
# Makefile for ./code/fluid/java/control
HERE=${FLUIDTOP}/code/fluid/java/control
SUBDIRS= 
JAVASRC= 	AnchoredBreakLabel.java \
		AnchoredContinueLabel.java \
		BreakLabel.java \
		CallExceptionLabel.java \
		CallInitializerLabel.java \
		CaughtExceptionLabel.java \
		ContinueLabel.java \
		ExceptionLabel.java \
		NamedBreakLabel.java \
		NamedContinueLabel.java \
		PrimitiveExceptionLabel.java \
		ReturnLabel.java \
		ThrownExceptionLabel.java

OBSOLETE= JavaComponentFactory.java

include ${FLUIDTOP}/lib/make/define.mk
include ${FLUIDTOP}/lib/make/rule.mk

all : ${JAVAOBJ}
