# $Header$
# Makefile for ./code/fluid/java/util

HERE=${FLUIDTOP}/code/fluid/java/util

SUBDIRS= 

JAVASRC=	\
		OpSearch.java \
		CogenUtil.java \
		TypeUtil.java \
		BindUtil.java \
		VisitUtil.java \
		PromiseUtil.java \

include ${FLUIDTOP}/lib/make/define.mk
include ${FLUIDTOP}/lib/make/rule.mk

all : ${JAVAOBJ}

