<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="visiomodel"
    nsURI="http://infai.org/visio2emf/" nsPrefix="visio">
  <eClassifiers xsi:type="ecore:EClass" name="EVisioIdElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visioID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EVisioNamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visioName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EVisioDocument" eSuperTypes="#//EVisioNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="visioPages" upperBound="-1"
        eType="#//EVisioPage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EVisioPage" eSuperTypes="#//EVisioShape"/>
  <eClassifiers xsi:type="ecore:EClass" name="EVisioShape" abstract="true" eSuperTypes="#//EVisioIdElement #//EVisioNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="visioSpatialContainedShapes"
        upperBound="-1" eType="#//EVisioShape"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visioContainedShapes" upperBound="-1"
        eType="#//EVisioShape" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visioAttributes" upperBound="-1"
        eType="#//EVisioAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visioText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visioShapeSheet" lowerBound="1"
        eType="#//EVisioShapeSheet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visioMasterShapeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visioMasterShapeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EVisioShapeWithoutMaster" eSuperTypes="#//EVisioShape"/>
  <eClassifiers xsi:type="ecore:EClass" name="EVisioAttribute" eSuperTypes="#//EVisioNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visioValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EVisioConnectionShape" eSuperTypes="#//EVisioShape">
    <eStructuralFeatures xsi:type="ecore:EReference" name="visioSourceShape" eType="#//EVisioShape"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visioTargetShape" eType="#//EVisioShape"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EVisioShapeSheet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="visioSections" upperBound="-1"
        eType="#//EVisioSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EVisioSection" eSuperTypes="#//EVisioNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="visioRows" upperBound="-1"
        eType="#//EVisioRow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EVisioRow" eSuperTypes="#//EVisioNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="visioCells" upperBound="-1"
        eType="#//EVisioCell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EVisioCell" eSuperTypes="#//EVisioNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visioValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visioFormula" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visioUnit" eType="#//EVisioeVisioUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EVisioeVisioUnit">
    <eLiterals name="viseVisioUnitString" value="231"/>
    <eLiterals name="visAngleUnit" value="80"/>
    <eLiterals name="visAcre" value="36"/>
    <eLiterals name="visCentimeters" value="69"/>
    <eLiterals name="visCicerosAndDidots" value="52"/>
    <eLiterals name="visCiceros" value="54"/>
    <eLiterals name="visCurrency" value="111"/>
    <eLiterals name="visDate" value="40"/>
    <eLiterals name="visDegreeMinSec" value="82"/>
    <eLiterals name="visDegrees" value="81"/>
    <eLiterals name="visDidots" value="53"/>
    <eLiterals name="visDrawingeVisioUnit" value="64"/>
    <eLiterals name="visDurationeVisioUnit" value="42"/>
    <eLiterals name="visElapsedDay" value="44"/>
    <eLiterals name="visElapsedHour" value="45"/>
    <eLiterals name="visElapsedMin" value="46"/>
    <eLiterals name="visElapsedSec" value="47"/>
    <eLiterals name="visElapsedWeek" value="43"/>
    <eLiterals name="visFeetAndInches" value="67"/>
    <eLiterals name="visFeet" value="66"/>
    <eLiterals name="visHectare" value="37"/>
    <eLiterals name="visInches" value="65"/>
    <eLiterals name="visInchFrac" value="73"/>
    <eLiterals name="visKilometers" value="72"/>
    <eLiterals name="visMeters" value="71"/>
    <eLiterals name="visMileFrac" value="74"/>
    <eLiterals name="visMiles" value="68"/>
    <eLiterals name="visMillimeters" value="70"/>
    <eLiterals name="visMin" value="84"/>
    <eLiterals name="visNautMiles" value="76"/>
    <eLiterals name="visNoCast" value="252"/>
    <eLiterals name="visNumber" value="32"/>
    <eLiterals name="visPageUnit" value="63"/>
    <eLiterals name="visPercent" value="33"/>
    <eLiterals name="visPicasAndPoints" value="49"/>
    <eLiterals name="visPicas" value="51"/>
    <eLiterals name="visPoints" value="50"/>
    <eLiterals name="visRadians" value="83"/>
    <eLiterals name="visSec" value="85"/>
    <eLiterals name="visTypeUnit" value="48"/>
    <eLiterals name="viseVisioUnitColor" value="251"/>
    <eLiterals name="viseVisioUnitGUID" value="95"/>
    <eLiterals name="viseVisioUnitInval" value="255"/>
    <eLiterals name="viseVisioUnitNURBS" value="138"/>
    <eLiterals name="viseVisioUnitPoint" value="225"/>
    <eLiterals name="viseVisioUnitPolyline" value="139"/>
    <eLiterals name="visYards" value="75"/>
  </eClassifiers>
</ecore:EPackage>
