# $Header: /cvs/fluid/fluid/code/fluid/control/GNUmakefile,v 1.18 1999/05/28 13:33:45 aarong Exp $
# Makefile for ./code/fluid/control
HERE=${FLUIDTOP}/code/fluid/control
JAVASRC=	Abort.java \
		AbruptExitPort.java \
		AddLabel.java \
		BackwardAnalysis.java \
		BackwardTransfer.java \
		BlankInputPort.java \
		BlankOutputPort.java \
		Choice.java \
		Component.java \
		ComponentAbruptExitPort.java \
		ComponentBlankAbruptExitPort.java \
		ComponentBlankEntryPort.java \
		ComponentBlankNormalExitPort.java \
		ComponentBooleanExitPort.java \
		ComponentChoice.java \
		ComponentEntryPort.java \
		ComponentFactory.java \
		ComponentFlow.java \
		ComponentNormalExitPort.java \
		ComponentPort.java \
		ComponentSink.java \
		ComponentSource.java \
		ControlEdge.java \
		ControlEdgeEnumeration.java \
		ControlFlowGraph.java \
		ControlLabel.java \
		ControlNode.java \
		DoubleInputPort.java \
		DoubleOutputPort.java \
		DynamicSplit.java \
		EdgeLinkageError.java \
		EmptyControlEdgeEnumeration.java \
		Entity.java \
		EntryPort.java \
		ExitPort.java \
		Flow.java \
		FlowAnalysis.java \
		Fork.java \
		ForwardAnalysis.java \
		ForwardTransfer.java \
		InputPort.java \
		Join.java \
		LabelList.java \
		LabelTest.java \
		Merge.java \
		Never.java \
		NoInput.java \
		NoOperation.java \
		NoOutput.java \
		NormalExitPort.java \
		OneInput.java \
		OneOutput.java \
		OutputPort.java \
		PairControlEdgeEnumeration.java \
		PendingLabelStrip.java \
		Port.java \
		SequenceComponent.java \
		SequenceSubcomponent.java \
		SimpleComponent.java \
		SimpleControlEdge.java \
		SimpleInputPort.java \
		SimpleOutputPort.java \
		SingleControlEdgeEnumeration.java \
		Sink.java \
		Source.java \
		Split.java \
		Subcomponent.java \
		SubcomponentAbruptExitPort.java \
		SubcomponentBooleanExitPort.java \
		SubcomponentChoice.java \
		SubcomponentEntryPort.java \
		SubcomponentFlow.java \
		SubcomponentNormalExitPort.java \
		SubcomponentPort.java \
		Test.java \
		TrackedDemerge.java \
		TrackedMerge.java \
		TrackLabel.java \
		TwoInput.java \
		TwoOutput.java \
		UnknownLabel.java \
		VariableComponent.java \
		VariableSubcomponent.java \
		VariableSubcomponentControlEdge.java

HTML=		package.html

OBSOLETE=	Atom.* \
		Lvalue.* \
		NullChoice.* \
		ReturnLabel.* \
		BreakLabel.* \
		NamedBreakLabel.* \
		ContinueLabel.* \
		NamedContinueLabel.* \
		MethodCall.* \
		MethodEntry.* \
		MethodExit.* \
        doc.html

include ${FLUIDTOP}/lib/make/define.mk
include ${FLUIDTOP}/lib/make/rule.mk

all : ${JAVAOBJ}
