/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package edu.toronto.cs.openome_model.validation;

import edu.toronto.cs.openome_model.Actor;
import edu.toronto.cs.openome_model.Association;
import edu.toronto.cs.openome_model.Intention;
import edu.toronto.cs.openome_model.Model;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link edu.toronto.cs.openome_model.Container}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContainerValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateSub(EList<Actor> value);
	boolean validateIntentions(EList<Intention> value);
	boolean validateModel(Model value);
	boolean validateAssociationTo(EList<Association> value);
	boolean validateAssociationFrom(EList<Association> value);
}
