/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package edu.toronto.cs.openome_model.validation;

import edu.toronto.cs.openome_model.Dependency;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link edu.toronto.cs.openome_model.Dependable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DependableValidator {
	boolean validate();

	boolean validateDependencyFrom(EList<Dependency> value);
	boolean validateDependencyTo(EList<Dependency> value);
}
