/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package edu.toronto.cs.openome_model.validation;

import edu.toronto.cs.openome_model.Alternative;
import edu.toronto.cs.openome_model.Association;
import edu.toronto.cs.openome_model.Container;
import edu.toronto.cs.openome_model.Contribution;
import edu.toronto.cs.openome_model.Correlation;
import edu.toronto.cs.openome_model.Decomposition;
import edu.toronto.cs.openome_model.Dependency;
import edu.toronto.cs.openome_model.Intention;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link edu.toronto.cs.openome_model.Model}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateIntentions(EList<Intention> value);
	boolean validateContributions(EList<Contribution> value);
	boolean validateDependencies(EList<Dependency> value);
	boolean validateDecompositions(EList<Decomposition> value);
	boolean validateContainers(EList<Container> value);
	boolean validateCorrelations(EList<Correlation> value);
	boolean validateAssociations(EList<Association> value);
	boolean validateAlternatives(EList<Alternative> value);
}
