/* Generated By:JavaCC: Do not edit this line. ParseError.java Version 0.6 */
package fluid.parse;

import fluid.FluidException;

public class ParseError extends FluidException {
  public ParseError() { super(); }
  public ParseError(String s) { super(s); }
}
