# $Header: /cvs/fluid/fluid/code/fluid/display/examples/GNUmakefile,v 1.2 1998/11/05 13:48:37 aarong Exp $
# Makefile for relative path from shadow directory
HERE= ${FLUIDTOP}/code/fluid/display/examples

SUBDIRS= 
JAVASRC=	tbex.java \
		tbex2.java \
		tbex3.java \
		TimeTextBean.java \
		ExerciseBean.java \
        ReadSerialized.java \
        SerializationTest.java

include ${FLUIDTOP}/lib/make/define.mk
include ${FLUIDTOP}/lib/make/rule.mk

.PHONY: all
all : ${JAVAOBJ}

